parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      py37_np116_sp016:
        PYTHON: '3.7'
        NUMPY: '1.16'
        SCIPY: '0.16'
        CONDA_ENV: 'testenv'

  steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: no
        packageSpecs: ''

    - script: |
        buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    - script: |
        buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        call activate %CONDA_ENV%
        pushd bin
        numba -s
        popd
        python -m numba.tests.test_runtests
        python runtests.py -m 2 -b -- numba.tests
      displayName: 'Test'
